// Oyi action truth -- shared interpretation of the canonical conversation
// action contract (Backend: src/oyi-core/actions/actionTruthProjection.ts).
//
// THIS FILE IS BYTE-IDENTICAL in Consumer (src/lib/oyiActionTruth.ts) and
// Facility (lib/oyiActionTruth.ts); both surfaces are tested against the
// same contract fixture (oyiActionTruth.fixture.json, generated by the
// Backend contract smoke). Change it in both places or neither.
//
// The rules it encodes:
//   - execution.action.status is the canonical OyiActionStatus. Only
//     "confirmed" means the result was VERIFIED.
//   - A user pressing Confirm is approval ("approved"), never verification.
//   - "provider_accepted" / "unobservable" mean the command was accepted
//     but Oyi could not verify the final physical state.
//   - Anything unknown renders as nothing rather than as success.

export const OYI_ACTION_STATUSES = [
  "draft",
  "awaiting_confirmation",
  "approved",
  "queued",
  "sent",
  "provider_accepted",
  "provider_rejected",
  "verifying",
  "confirmed",
  "unobservable",
  "timed_out",
  "failed",
  "cancelled",
  "superseded",
] as const;

export type OyiActionStatus = (typeof OYI_ACTION_STATUSES)[number];

export type OyiActionTruthTone = "awaiting" | "progress" | "verified" | "unverified" | "failed" | "closed";

export type OyiConversationAction = {
  action_id: string;
  status: OyiActionStatus;
  requested_operation: string | null;
  requested_state: boolean | null;
  target_label: string | null;
  truth: Record<string, string | boolean> | null;
};

export type OyiActionTruthView = {
  status: OyiActionStatus;
  label: string;
  detail: string;
  tone: OyiActionTruthTone;
  verified: boolean;
  terminal: boolean;
  awaiting_user: boolean;
  target_label: string | null;
};

const VIEWS: Record<OyiActionStatus, { label: string; detail: string; tone: OyiActionTruthTone; terminal: boolean }> = {
  draft: { label: "Preparing action", detail: "Nothing has been sent yet.", tone: "awaiting", terminal: false },
  awaiting_confirmation: { label: "Confirm action?", detail: "Nothing has been sent yet. Oyi will act only after you confirm.", tone: "awaiting", terminal: false },
  approved: { label: "Approved", detail: "You approved this action. Oyi has not verified the result yet.", tone: "progress", terminal: false },
  queued: { label: "Sending", detail: "The command is being sent. It has not been verified yet.", tone: "progress", terminal: false },
  sent: { label: "Sent", detail: "The command was sent. It has not been verified yet.", tone: "progress", terminal: false },
  provider_accepted: { label: "Command accepted", detail: "The device provider accepted the command. Oyi has not verified the final physical state yet.", tone: "unverified", terminal: false },
  verifying: { label: "Verifying", detail: "Oyi is checking the final device state.", tone: "progress", terminal: false },
  confirmed: { label: "Verified", detail: "Oyi verified the final device state.", tone: "verified", terminal: true },
  unobservable: { label: "Command accepted", detail: "Oyi could not verify the final physical state.", tone: "unverified", terminal: true },
  timed_out: { label: "Not verified", detail: "Oyi did not receive confirmation in time. Do not assume the change happened.", tone: "failed", terminal: true },
  failed: { label: "Action failed", detail: "The command did not complete. Nothing is confirmed as changed.", tone: "failed", terminal: true },
  provider_rejected: { label: "Rejected by provider", detail: "The device provider did not accept the command.", tone: "failed", terminal: true },
  cancelled: { label: "Cancelled", detail: "Nothing was sent.", tone: "closed", terminal: true },
  superseded: { label: "Replaced", detail: "A newer request replaced this action.", tone: "closed", terminal: true },
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function isActionStatus(value: unknown): value is OyiActionStatus {
  return typeof value === "string" && (OYI_ACTION_STATUSES as readonly string[]).includes(value);
}

function readAction(raw: unknown): OyiConversationAction | null {
  if (!isRecord(raw) || !isActionStatus(raw.status) || typeof raw.action_id !== "string" || !raw.action_id) return null;
  const target = isRecord(raw.target) ? raw.target : {};
  const truth: Record<string, string | boolean> = {};
  if (isRecord(raw.truth)) {
    for (const [key, value] of Object.entries(raw.truth)) {
      if (typeof value === "string" || typeof value === "boolean") truth[key] = value;
    }
  }
  return {
    action_id: raw.action_id,
    status: raw.status,
    requested_operation: typeof raw.requested_operation === "string" ? raw.requested_operation : null,
    requested_state: typeof raw.requested_state === "boolean" ? raw.requested_state : null,
    target_label: typeof target.label === "string" && target.label.trim() ? target.label.trim() : null,
    truth: Object.keys(truth).length ? truth : null,
  };
}

// Reads the canonical action from a live response's `execution` object, or
// from a restored message's metadata (persistence stores it as
// metadata.action next to metadata.workflow).
export function conversationActionFrom(source: unknown): OyiConversationAction | null {
  if (!isRecord(source)) return null;
  if (isRecord(source.execution) && source.execution.action !== undefined) return readAction(source.execution.action);
  return readAction(source.action);
}

export function actionTruthView(source: unknown): OyiActionTruthView | null {
  const action = conversationActionFrom(source);
  if (!action) return null;
  const view = VIEWS[action.status];
  return {
    status: action.status,
    label: view.label,
    detail: view.detail,
    tone: view.tone,
    verified: action.status === "confirmed",
    terminal: view.terminal,
    awaiting_user: action.status === "awaiting_confirmation",
    target_label: action.target_label,
  };
}

// The message state a surface should use for this action outcome.
export function messageStateForActionView(view: OyiActionTruthView | null): "approval_required" | "executing" | "action_confirmed" | "action_failed" | "partial" | "informational" | null {
  if (!view) return null;
  if (view.awaiting_user) return "approval_required";
  if (view.tone === "verified") return "action_confirmed";
  if (view.tone === "failed") return "action_failed";
  if (view.tone === "unverified") return "partial";
  if (view.tone === "progress") return "executing";
  return "informational";
}

// Honest fallback copy for a turn that returned no text at all.
export const OYI_EMPTY_RESPONSE_TEXT = "Oyi did not return an answer for this request.";
